apiVersion: skaffold/v4beta8
kind: Config
deploy:
  kubectl:
    remoteManifests:
      - ./infra/k8s/*
metadata:
  name: photo-gallery
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: photo-gallery-409812
  artifacts:
    - image: us.gcr.io/photo-gallery-409812/event-bus
      context: Event-Bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: us.gcr.io/photo-gallery-409812/storagemgmtserv
      context: StorageMgmtServ
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: us.gcr.io/photo-gallery-409812/usagemntrserv
      context: UsageMntrServ
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: us.gcr.io/photo-gallery-409812/useraccmgmtserv
      context: UserAccMgmtServ
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: us.gcr.io/photo-gallery-409812/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: us.gcr.io/photo-gallery-409812/logserv
      context: LogServ
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
manifests:
  rawYaml:
    - infra/k8s/event-bus-depl.yaml
    - infra/k8s/ingress-serv.yaml
    - infra/k8s/log-serv-depl.yaml
    - infra/k8s/storage-mgmt-serv-depl.yaml
    - infra/k8s/usage-mntr-serv-depl.yaml
    - infra/k8s/user-acc-mgmt-serv-depl.yaml
    - infra/k8s/frontend-depl.yaml