apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-serv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: photo-gallery.com
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: frontend-serv
              port:
                number: 3000
        - path: /register
          pathType: ImplementationSpecific
          backend:
            service:
              name: user-acc-mgmt-serv
              port:
                number: 5000
        - path: /login
          pathType: ImplementationSpecific
          backend:
            service:
              name: user-acc-mgmt-serv
              port:
                number: 5000
        - path: /images/upload
          pathType: ImplementationSpecific
          backend:
            service:
              name: storage-mgmt-serv
              port:
                number: 5001
        - path: /images/?(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: storage-mgmt-serv
              port:
                number: 5001
        - path: /images/delete
          pathType: ImplementationSpecific
          backend:
            service:
              name: storage-mgmt-serv
              port:
                number: 5001
        - path: /getUserStorage/?(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: usage-mntr-serv
              port:
                number: 5002