apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-serv-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-serv
  template:
    metadata:
      labels:
        app: log-serv
    spec:
      containers:
        - name: log-serv
          image: us.gcr.io/photo-gallery-409812/logserv
          # image: itsmefrost/logserv
---
apiVersion: v1
kind: Service
metadata:
  name: log-serv
spec:
  selector:
    app: log-serv
  ports:
    - name: log-serv
      protocol: TCP
      port: 5004
      targetPort: 5004